export const PRESET_EXERCISES = [
  { id: 'bb_bench',     name: 'Barbell Bench Press',         sets: 4 },
  { id: 'sm_squat',     name: 'Smith Machine Squat',         sets: 4 },
  { id: 'lat_pull',     name: 'Lat Pulldown',                sets: 3 },
  { id: 'db_rdl',       name: 'DB Romanian Deadlift',        sets: 3 },
  { id: 'db_lat_raise', name: 'DB Lateral Raise',            sets: 3 },
  { id: 'db_hammer',    name: 'DB Hammer Curls',             sets: 3 },
  { id: 'sm_incline',   name: 'Smith Machine Incline Press', sets: 4 },
  { id: 'bb_row',       name: 'Barbell Row',                 sets: 4 },
  { id: 'db_goblet',    name: 'DB Goblet Squat',             sets: 3 },
  { id: 'db_ohp',       name: 'Seated DB Shoulder Press',    sets: 3 },
  { id: 'sa_lat_pull',  name: 'Single-Arm Lat Pulldown',     sets: 3 },
  { id: 'tri_ext',      name: 'Tricep Overhead Extension',   sets: 3 },
  { id: 'bb_squat',     name: 'Barbell Squat',               sets: 4 },
  { id: 'bb_deadlift',  name: 'Barbell Deadlift',            sets: 3 },
  { id: 'bb_ohp',       name: 'Barbell Overhead Press',      sets: 4 },
  { id: 'pull_up',      name: 'Pull-Up',                     sets: 3 },
  { id: 'dip',          name: 'Dip',                         sets: 3 },
  { id: 'leg_press',    name: 'Leg Press',                   sets: 4 },
  { id: 'leg_curl',     name: 'Leg Curl',                    sets: 3 },
  { id: 'leg_ext',      name: 'Leg Extension',               sets: 3 },
  { id: 'cable_row',    name: 'Cable Row',                   sets: 3 },
  { id: 'chest_fly',    name: 'Cable Chest Fly',             sets: 3 },
  { id: 'face_pull',    name: 'Face Pull',                   sets: 3 },
  { id: 'db_curl',      name: 'DB Bicep Curl',               sets: 3 },
  { id: 'db_tricep',    name: 'DB Tricep Kickback',          sets: 3 },
  { id: 'calf_raise',   name: 'Calf Raise',                  sets: 4 },
  { id: 'ab_crunch',    name: 'Cable Crunch',                sets: 3 },
  { id: 'hip_thrust',   name: 'Hip Thrust',                  sets: 4 },
];

export const WORKOUTS = {
  A: [
    { id: 'bb_bench',     name: 'Barbell Bench Press',         sets: 4 },
    { id: 'sm_squat',     name: 'Smith Machine Squat',         sets: 4 },
    { id: 'lat_pull',     name: 'Lat Pulldown',                sets: 3 },
    { id: 'db_rdl',       name: 'DB Romanian Deadlift',        sets: 3 },
    { id: 'db_lat_raise', name: 'DB Lateral Raise',            sets: 3 },
    { id: 'db_hammer',    name: 'DB Hammer Curls',             sets: 3 },
  ],
  B: [
    { id: 'sm_incline',   name: 'Smith Machine Incline Press', sets: 4 },
    { id: 'bb_row',       name: 'Barbell Row',                 sets: 4 },
    { id: 'db_goblet',    name: 'DB Goblet Squat',             sets: 3 },
    { id: 'db_ohp',       name: 'Seated DB Shoulder Press',    sets: 3 },
    { id: 'sa_lat_pull',  name: 'Single-Arm Lat Pulldown',     sets: 3 },
    { id: 'tri_ext',      name: 'Tricep Overhead Extension',   sets: 3 },
  ],
};
