export const PRESET_EXERCISES = [
  { id: 'bb_bench',     name: 'Barbell Bench Press'         },
  { id: 'sm_squat',     name: 'Smith Machine Squat'         },
  { id: 'lat_pull',     name: 'Lat Pulldown'                },
  { id: 'db_rdl',       name: 'DB Romanian Deadlift'        },
  { id: 'db_lat_raise', name: 'DB Lateral Raise'            },
  { id: 'db_hammer',    name: 'DB Hammer Curls'             },
  { id: 'sm_incline',   name: 'Smith Machine Incline Press' },
  { id: 'bb_row',       name: 'Barbell Row'                 },
  { id: 'db_goblet',    name: 'DB Goblet Squat'             },
  { id: 'db_ohp',       name: 'Seated DB Shoulder Press'    },
  { id: 'sa_lat_pull',  name: 'Single-Arm Lat Pulldown'     },
  { id: 'tri_ext',      name: 'Tricep Overhead Extension'   },
  { id: 'bb_squat',     name: 'Barbell Squat'               },
  { id: 'bb_deadlift',  name: 'Barbell Deadlift'            },
  { id: 'bb_ohp',       name: 'Barbell Overhead Press'      },
  { id: 'pull_up',      name: 'Pull-Up'                     },
  { id: 'dip',          name: 'Dip'                         },
  { id: 'leg_press',    name: 'Leg Press'                   },
  { id: 'leg_curl',     name: 'Leg Curl'                    },
  { id: 'leg_ext',      name: 'Leg Extension'               },
  { id: 'cable_row',    name: 'Cable Row'                   },
  { id: 'chest_fly',    name: 'Cable Chest Fly'             },
  { id: 'face_pull',    name: 'Face Pull'                   },
  { id: 'db_curl',      name: 'DB Bicep Curl'               },
  { id: 'db_tricep',    name: 'DB Tricep Kickback'          },
  { id: 'calf_raise',   name: 'Calf Raise'                  },
  { id: 'ab_crunch',    name: 'Cable Crunch'                },
  { id: 'hip_thrust',   name: 'Hip Thrust'                  },
];

// Used only to seed a new user's first workouts — not referenced at runtime.
export const DEFAULT_WORKOUTS = [
  {
    id: 'workout_a',
    label: 'A',
    color: 'a',
    exercises: [
      { id: 'bb_bench',     name: 'Barbell Bench Press',         sets: 4 },
      { id: 'sm_squat',     name: 'Smith Machine Squat',         sets: 4 },
      { id: 'lat_pull',     name: 'Lat Pulldown',                sets: 3 },
      { id: 'db_rdl',       name: 'DB Romanian Deadlift',        sets: 3 },
      { id: 'db_lat_raise', name: 'DB Lateral Raise',            sets: 3 },
      { id: 'db_hammer',    name: 'DB Hammer Curls',             sets: 3 },
    ],
  },
  {
    id: 'workout_b',
    label: 'B',
    color: 'b',
    exercises: [
      { id: 'sm_incline',   name: 'Smith Machine Incline Press', sets: 4 },
      { id: 'bb_row',       name: 'Barbell Row',                 sets: 4 },
      { id: 'db_goblet',    name: 'DB Goblet Squat',             sets: 3 },
      { id: 'db_ohp',       name: 'Seated DB Shoulder Press',    sets: 3 },
      { id: 'sa_lat_pull',  name: 'Single-Arm Lat Pulldown',     sets: 3 },
      { id: 'tri_ext',      name: 'Tricep Overhead Extension',   sets: 3 },
    ],
  },
];
